/**
 * @fleetos/acceptance-field — journeys: field mode (offline tolerance) +
 * connectivity postures + edge commands.
 */

import type { AcceptanceJourney } from "../journey-contracts.js";
import { AST_TRAILER, AST_TRUCK, DEV_GATEWAY, DEV_TELEMETRY, T0 } from "../fixtures.js";

export const fieldModeOfflineJourney: AcceptanceJourney = {
  id: "field-mode-offline-tolerance",
  persona: "field-technician",
  capability: "field-mode",
  goal: "Operate in the field with last-known data: the phone view never claims freshness for stale data, declares last-known sections, and bounds every section.",
  steps: [
    { id: "t1", summary: "admit the truck", op: { kind: "asset.admit", assetId: AST_TRUCK, assetKind: "vehicle", displayName: "Truck Alpha 01" } },
    { id: "t2", summary: "admit the trailer", op: { kind: "asset.admit", assetId: AST_TRAILER, assetKind: "handheld", displayName: "Trailer Beta 02" } },
    { id: "t3", summary: "enroll the telemetry device", op: { kind: "device.enroll", deviceId: DEV_TELEMETRY, assetId: AST_TRUCK, serial: "SN-1001" } },
    { id: "t4", summary: "enroll the gateway device", op: { kind: "device.enroll", deviceId: DEV_GATEWAY, assetId: AST_TRAILER, serial: "SN-2002" } },
    { id: "t5", summary: "three error observations (escalates to critical)", op: { kind: "observation.ingest-batch", deviceId: DEV_TELEMETRY, fromSeq: 1, count: 3, observationKind: "health.error", firstObservedAt: T0 + 1_000, stepMs: 10_000 } },
    { id: "t6", summary: "one warning on the gateway", op: { kind: "observation.ingest", deviceId: DEV_GATEWAY, seq: 1, observedAt: T0 + 2_000, observationKind: "health.warn", payload: { code: "gw-01" } } },
    { id: "t7", summary: "triage into findings", op: { kind: "health.triage" } },
    { id: "t8", summary: "record a connectivity heartbeat for the gateway", op: { kind: "connectivity.record", deviceId: DEV_GATEWAY, state: "online", observedAt: T0 + 3_000 } },
    {
      id: "t9",
      summary: "assemble the field view OFFLINE (5 min later) with tight phone limits",
      op: { kind: "view.field-mode", now: T0 + 300_000, limits: { alerts: 1, recoveries: 5, maintenance: 5, connectivity: 1, attributeKeys: 4 } },
    },
  ],
  assertions: [
    { id: "f1", description: "the offline field view assembled", reading: "t9.field.ok", op: "deep-equals", expected: true },
    { id: "f2", description: "the view digest verifies (tamper-evident)", reading: "t9.field.digestVerified", op: "deep-equals", expected: true },
    { id: "f3", description: "alerts are bounded to the phone limit", reading: "t9.field.alerts", op: "deep-equals", expected: 1 },
    { id: "f4", description: "the alert section reports truncation", reading: "t9.field.connectivityTruncated", op: "deep-equals", expected: true },
    { id: "f5", description: "the top alert is the escalated critical", reading: "t9.field.alert0.severity", op: "deep-equals", expected: "critical" },
    { id: "f6", description: "NEVER claims freshness: last-known provenance is stale", reading: "t9.field.alert0.lastKnownStaleness", op: "deep-equals", expected: "stale" },
    { id: "f7", description: "both non-fresh sections are declared last-known", reading: "t9.field.lastKnownSections", op: "deep-equals", expected: ["top-alerts", "connectivity-status"] },
    { id: "f8", description: "every section respects its size bound (phone shape)", reading: "t9.field.sectionsBounded", op: "deep-equals", expected: true },
    { id: "f9", description: "the stale online heartbeat downgrades to degraded (honest posture)", reading: "t9.field.connectivityPostures", op: "deep-equals", expected: ["degraded"] },
    { id: "f10", description: "the connectivity entry's last-known is stale", reading: "t9.field.connectivityLastKnown", op: "deep-equals", expected: ["stale"] },
    { id: "f11", description: "alert ordering is priority ordered", reading: "t9.field.alertOrderIsPriority", op: "deep-equals", expected: true },
    { id: "f12", description: "connectivity attribute excerpts are bounded", reading: "t9.field.connectivityAttributesBounded", op: "deep-equals", expected: true },
    { id: "f13", description: "no findings were fabricated by triage", reading: "t7.triage.count", op: "deep-equals", expected: 2 },
  ],
};

export const connectivityPostureJourney: AcceptanceJourney = {
  id: "connectivity-postures",
  persona: "edge-operator",
  capability: "connectivity",
  goal: "Drive connectivity intents through the real lifecycle and read honest posture rollups: aligned, divergent and unknown — never guessed.",
  steps: [
    { id: "t1", summary: "admit the asset", op: { kind: "asset.admit", assetId: AST_TRUCK, assetKind: "vehicle", displayName: "Truck Alpha 01" } },
    { id: "t2", summary: "enroll the telemetry device", op: { kind: "device.enroll", deviceId: DEV_TELEMETRY, assetId: AST_TRUCK, serial: "SN-1001" } },
    { id: "t3", summary: "enroll the gateway device", op: { kind: "device.enroll", deviceId: DEV_GATEWAY, assetId: AST_TRUCK, serial: "SN-2002" } },
    { id: "t4", summary: "record the telemetry heartbeat online", op: { kind: "connectivity.record", deviceId: DEV_TELEMETRY, state: "online", observedAt: T0 + 1_000 } },
    { id: "t5", summary: "record the gateway heartbeat online", op: { kind: "connectivity.record", deviceId: DEV_GATEWAY, state: "online", observedAt: T0 + 2_000 } },
    { id: "t6", summary: "propose an online intent for the telemetry device", op: { kind: "connectivity.propose-intent", deviceId: DEV_TELEMETRY, desiredState: "online", idempotencyKey: "conn-telemetry-online-01" } },
    {
      id: "t7",
      summary: "authorize WITHOUT a Guardian grant must be refused",
      expectRefusal: true,
      op: { kind: "connectivity.transition-intent", idempotencyKey: "conn-telemetry-online-01", eventKind: "authorize", grant: null, ceiling: { effect: "allow", reason: "operator policy allows" } },
    },
    {
      id: "t8",
      summary: "authorize against a DENY ceiling must be refused (Guardian cannot be bypassed)",
      expectRefusal: true,
      op: {
        kind: "connectivity.transition-intent",
        idempotencyKey: "conn-telemetry-online-01",
        eventKind: "authorize",
        grant: { grantedBy: "guardian", authorizationDigest: "sha256:grant-01", grantedAt: T0, expiresAt: T0 + 3_600_000 },
        ceiling: { effect: "deny", reason: "policy denies this device class" },
      },
    },
    {
      id: "t9",
      summary: "authorize with grant + allow ceiling",
      op: {
        kind: "connectivity.transition-intent",
        idempotencyKey: "conn-telemetry-online-01",
        eventKind: "authorize",
        grant: { grantedBy: "guardian", authorizationDigest: "sha256:grant-01", grantedAt: T0, expiresAt: T0 + 3_600_000 },
        ceiling: { effect: "allow", reason: "operator policy allows" },
      },
    },
    { id: "t10", summary: "activate the authorized intent", op: { kind: "connectivity.transition-intent", idempotencyKey: "conn-telemetry-online-01", eventKind: "activate" } },
    { id: "t11", summary: "rollup: telemetry aligned online", op: { kind: "connectivity.rollup-posture" } },
    { id: "t12", summary: "propose an online intent for the gateway", op: { kind: "connectivity.propose-intent", deviceId: DEV_GATEWAY, desiredState: "online", idempotencyKey: "conn-gateway-online-02" } },
    {
      id: "t13",
      summary: "authorize + activate the gateway intent",
      op: {
        kind: "connectivity.transition-intent",
        idempotencyKey: "conn-gateway-online-02",
        eventKind: "authorize",
        grant: { grantedBy: "guardian", authorizationDigest: "sha256:grant-02", grantedAt: T0, expiresAt: T0 + 3_600_000 },
        ceiling: { effect: "allow", reason: "operator policy allows" },
      },
    },
    { id: "t14", summary: "activate the gateway intent", op: { kind: "connectivity.transition-intent", idempotencyKey: "conn-gateway-online-02", eventKind: "activate" } },
    { id: "t15", summary: "the gateway goes OFFLINE against its desired-online intent", op: { kind: "connectivity.record", deviceId: DEV_GATEWAY, state: "offline", observedAt: T0 + 6_000 } },
    { id: "t16", summary: "rollup: one aligned, one divergent", op: { kind: "connectivity.rollup-posture" } },
  ],
  assertions: [
    { id: "c1", description: "both heartbeats were recorded", reading: "t5.conn.state", op: "deep-equals", expected: "online" },
    { id: "c2", description: "authorize without a grant is refused (authorization-required)", reading: "t7.intent.refused", op: "deep-equals", expected: "authorization-required" },
    { id: "c3", description: "a deny ceiling refuses (policy-denied — Guardian law)", reading: "t8.intent.refused", op: "deep-equals", expected: "policy-denied" },
    { id: "c4", description: "grant + allow ceiling authorizes the intent", reading: "t9.intent.state", op: "deep-equals", expected: "authorized" },
    { id: "c5", description: "activation moved the intent to active", reading: "t10.intent.state", op: "deep-equals", expected: "active" },
    { id: "c6", description: "rollup sees both devices", reading: "t11.rollup.total", op: "deep-equals", expected: 2 },
    { id: "c7", description: "the telemetry intent is aligned with its online heartbeat", reading: "t11.rollup.aligned", op: "deep-equals", expected: 1 },
    { id: "c8", description: "the gateway has no intent yet: unknown, never guessed", reading: "t11.rollup.unknown", op: "deep-equals", expected: 1 },
    { id: "c9", description: "no divergence before the gateway intent exists", reading: "t11.rollup.divergent", op: "deep-equals", expected: 0 },
    { id: "c10", description: "the rollup digest verifies (tamper-evident)", reading: "t11.rollup.digestVerified", op: "deep-equals", expected: true },
    { id: "c11", description: "both observed heartbeats are online", reading: "t11.rollup.observedOnline", op: "deep-equals", expected: 2 },
    { id: "c12", description: "the gateway intent is active", reading: "t14.intent.state", op: "deep-equals", expected: "active" },
    { id: "c13", description: "after going offline: exactly one divergent posture", reading: "t16.rollup.divergent", op: "deep-equals", expected: 1 },
    { id: "c14", description: "the telemetry posture stays aligned", reading: "t16.rollup.aligned", op: "deep-equals", expected: 1 },
    { id: "c15", description: "the gateway (first device) shows desired online", reading: "t16.rollup.firstDesired", op: "deep-equals", expected: "online" },
    { id: "c16", description: "the gateway (first device) shows observed offline", reading: "t16.rollup.firstObserved", op: "deep-equals", expected: "offline" },
    { id: "c17", description: "the gateway alignment is honestly divergent", reading: "t16.rollup.firstAlignment", op: "deep-equals", expected: "divergent" },
    { id: "c18", description: "the first device's active intent state surfaces", reading: "t16.rollup.firstIntentState", op: "deep-equals", expected: "active" },
  ],
};

export const edgeCommandJourney: AcceptanceJourney = {
  id: "edge-command-lifecycle",
  persona: "edge-operator",
  capability: "edge-command",
  goal: "Issue an ADCOS command through the REAL lifecycle (issue -> dispatch -> ack -> result -> reconcile), verify its journal, and see the health rollup reflect the outcomes honestly.",
  steps: [
    { id: "t1", summary: "admit the asset", op: { kind: "asset.admit", assetId: AST_TRUCK, assetKind: "vehicle", displayName: "Truck Alpha 01" } },
    { id: "t2", summary: "enroll the device", op: { kind: "device.enroll", deviceId: DEV_TELEMETRY, assetId: AST_TRUCK, serial: "SN-1001" } },
    { id: "t3", summary: "issue a ping command", op: { kind: "adcos.issue", deviceId: DEV_TELEMETRY, commandKind: "ping", idempotencyKey: "edge-ping-01" } },
    { id: "t4", summary: "re-issue the same key — must dedup, not duplicate", op: { kind: "adcos.issue", deviceId: DEV_TELEMETRY, commandKind: "ping", idempotencyKey: "edge-ping-01" } },
    { id: "t5", summary: "dispatch the command", op: { kind: "adcos.dispatch", idempotencyKey: "edge-ping-01" } },
    { id: "t6", summary: "the edge acknowledges", op: { kind: "adcos.ack", idempotencyKey: "edge-ping-01", requestId: "req-0001" } },
    { id: "t7", summary: "the command succeeds", op: { kind: "adcos.result", idempotencyKey: "edge-ping-01", ok: true } },
    { id: "t8", summary: "reconcile the completed command", op: { kind: "adcos.reconcile", idempotencyKey: "edge-ping-01" } },
    { id: "t9", summary: "adapter health rollup over the fresh outcome window", op: { kind: "adcos.health-rollup", now: T0 + 60_000 } },
    {
      id: "t10",
      summary: "issue a reboot with an ack deadline",
      op: { kind: "adcos.issue", deviceId: DEV_TELEMETRY, commandKind: "reboot", idempotencyKey: "edge-reboot-02", expiresAt: T0 + 10_000_000 },
    },
    { id: "t11", summary: "dispatch the reboot to the edge", op: { kind: "adcos.dispatch", idempotencyKey: "edge-reboot-02" } },
    {
      id: "t12",
      summary: "a transient dispatch failure climbs the backoff ladder",
      op: { kind: "adcos.dispatch-failure", idempotencyKey: "edge-reboot-02", code: "provider-unavailable" },
    },
    { id: "t13", summary: "the deadline passes: the expired sweep terminates the command", op: { kind: "adcos.expire", now: T0 + 20_000_000 } },
    { id: "t14", summary: "health rollup long after the evidence window (honest degradation)", op: { kind: "adcos.health-rollup", now: T0 + 20_001_000 } },
  ],
  assertions: [
    { id: "a1", description: "the ping command was issued", reading: "t3.cmd.duplicate", op: "deep-equals", expected: false },
    { id: "a2", description: "the same key re-issues as a duplicate (idempotent dedup)", reading: "t4.cmd.duplicate", op: "deep-equals", expected: true },
    { id: "a3", description: "the re-issue returns the SAME command id", reading: "t4.cmd.id", op: "reading-equals", expected: "t3.cmd.id" },
    { id: "a4", description: "dispatch moved the phase to dispatched on attempt 1", reading: "t5.cmd.attempts", op: "deep-equals", expected: 1 },
    { id: "a5", description: "ack moved the phase to acknowledged", reading: "t6.cmd.phase", op: "deep-equals", expected: "acknowledged" },
    { id: "a6", description: "the ack carries the edge request id", reading: "t6.cmd.requestId", op: "deep-equals", expected: "req-0001" },
    { id: "a7", description: "the result moved the phase to resulted", reading: "t7.cmd.phase", op: "deep-equals", expected: "resulted" },
    { id: "a8", description: "the result is a success", reading: "t7.cmd.resultOk", op: "deep-equals", expected: true },
    { id: "a9", description: "reconcile completed the lifecycle (terminal phase)", reading: "t8.cmd.phase", op: "deep-equals", expected: "reconciled" },
    { id: "a10", description: "the command journal verifies (seq + audit chain)", reading: "t9.adcos.journalVerified", op: "deep-equals", expected: true },
    { id: "a11", description: "the fresh-window health rollup sees the outcome", reading: "t9.adcos.health.total", op: "deep-equals", expected: 1 },
    { id: "a12", description: "no failures in the fresh window", reading: "t9.adcos.health.failures", op: "deep-equals", expected: 0 },
    { id: "a13", description: "the adapter reports healthy with real evidence", reading: "t9.adcos.health.status", op: "deep-equals", expected: "healthy" },
    { id: "a14", description: "the circuit is closed after the success", reading: "t9.adcos.health.circuit", op: "deep-equals", expected: "closed" },
    { id: "a15", description: "the reboot dispatched on its first attempt", reading: "t11.cmd.attempts", op: "deep-equals", expected: 1 },
    { id: "a16", description: "the transient failure returned to issued with the base backoff", reading: "t12.cmd.backoffMs", op: "deep-equals", expected: 100 },
    { id: "a17", description: "the expired sweep terminated the overdue command", reading: "t13.adcos.expired", op: "length-eq", expected: 1 },
    { id: "a18", description: "outside the evidence window the adapter degrades honestly", reading: "t14.adcos.health.status", op: "deep-equals", expected: "degraded" },
    { id: "a19", description: "the honest reason is no-observations (never exaggerated)", reading: "t14.adcos.health.reasons", op: "deep-equals", expected: ["no-observations"] },
    { id: "a20", description: "the journal still verifies after expiry + degradation", reading: "t14.adcos.journalVerified", op: "deep-equals", expected: true },
    { id: "a21", description: "the late health report digest verifies", reading: "t14.adcos.health.digestVerified", op: "deep-equals", expected: true },
    { id: "a22", description: "the dispatch moved the command to the dispatched phase", reading: "t5.cmd.phase", op: "deep-equals", expected: "dispatched" },
  ],
};
